name: install_plugin_v2
description: A flutter plugin for install apk for android;
version: 1.0.0
homepage: https://github.com/youxiachai/flutter_install_plugin

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.youxiachai.installplugin
        pluginClass: InstallPlugin

dev_dependencies:
  flutter_lints: ^1.0.1
  flutter_test:
    sdk: flutter
